clc;
close all;
clear all;

% Name the images obrtained by running templates.m according to their alphabets or letters
% After renaming only this matlab code should be run
% All images should be present in this directory only
orig=imread('B.jpg');
a0=imread('0.jpg');
a0=imresize(a0,size(orig));
a1=imread('1.jpg');
a1=imresize(a1,size(orig));
a2=imread('2.jpg');
a2=imresize(a2,size(orig));
a3=imread('3.jpg');
a3=imresize(a3,size(orig));
a4=imread('4.jpg');
a4=imresize(a4,size(orig));
a5=imread('5.jpg');
a5=imresize(a5,size(orig));
a6=imread('6.jpg');
a6=imresize(a6,size(orig));
a7=imread('7.jpg');
a7=imresize(a7,size(orig));
a8=imread('8.jpg');
a8=imresize(a8,size(orig));
a9=imread('9.jpg');
a9=imresize(a9,size(orig));
aA=imread('A.jpg');
aA=imresize(aA,size(orig));
aB=imread('B.jpg');
aB=imresize(aB,size(orig));
aC=imread('C.jpg');
aC=imresize(aC,size(orig));
aD=imread('D.jpg');
aD=imresize(aD,size(orig));
aE=imread('E.jpg');
aE=imresize(aE,size(orig));
aF=imread('F.jpg');
aF=imresize(aF,size(orig));
aG=imread('G.jpg');
aG=imresize(aG,size(orig));
aH=imread('H.jpg');
aH=imresize(aH,size(orig));
aI=imread('I.jpg');
aI=imresize(aI,size(orig));
aJ=imread('J.jpg');
aJ=imresize(aJ,size(orig));
aK=imread('K.jpg');
aK=imresize(aK,size(orig));
aL=imread('L.jpg');
aL=imresize(aL,size(orig));
aM=imread('M.jpg');
aM=imresize(aM,size(orig));
aN=imread('N.jpg');
aN=imresize(aN,size(orig));
aO=imread('O.jpg');
aO=imresize(aO,size(orig));
aP=imread('P.jpg');
aP=imresize(aP,size(orig));
aQ=imread('Q.jpg');
aQ=imresize(aQ,size(orig));
aR=imread('R.jpg');
aR=imresize(aR,size(orig));
aS=imread('S.jpg');
aS=imresize(aS,size(orig));
aT=imread('T.jpg');
aT=imresize(aT,size(orig));
aU=imread('U.jpg');
aU=imresize(aU,size(orig));
aV=imread('V.jpg');
aV=imresize(aV,size(orig));
aW=imread('W.jpg');
aW=imresize(aW,size(orig));
aX=imread('X.jpg');
aX=imresize(aX,size(orig));
aY=imread('Y.jpg');
aY=imresize(aY,size(orig));
aZ=imread('Z.jpg');
aZ=imresize(aZ,size(orig));
% These are for different font structure
%aa4 = imread('aa4.jpg');
%aa4 = imresize(aa4,size(orig));
%aaM = imread('aaM.jpg');
%aaM = imresize(aaM,size(orig));
%aaI = imread('aaI.jpg');
%aaI = imresize(aaI,size(orig));